using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace ProjectEulerSolutions
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class Problem002
    {
        public void run()
        {
            //Create a stopwatch to calculate how long program takes to execute
            var watch = Stopwatch.StartNew();

            //Variables to hold numbers in fibonachi sequence and all even terms.
            long termOne = 1;
            long termTwo = 2;
            List<long> evenTerms = new List<long>();
            evenTerms.Add(termTwo);
            long nextTerm = 0;
            //Find all fibonacci numbers below 4000000 add even ones to the list.
            while (true)
            {
                nextTerm = termOne + termTwo;
                if (nextTerm > 4000000)
                    break;
                if(nextTerm % 2 == 0)
                    evenTerms.Add(nextTerm);
                termOne = termTwo;
                termTwo = nextTerm;
            }
            //Add all of the even terms together
            long totalSum = 0;
            foreach (long i in evenTerms)
                totalSum += i;
            //Display the totalSum of all even fibonacci numbers under 4000000 to user
            Console.WriteLine("The total sum of all even fibonacci under 4million is : " + totalSum);

            //Display time taken to execute program
            watch.Stop();
            var elapsedMs = watch.ElapsedMilliseconds;
            Console.Out.Write("Program completed in : " + elapsedMs + "ms");
        }
    }
}